#ifndef GSTYLEDEF_H
#define GSTYLEDEF_H

#define MUSIC_PLAYER_WIDTH 480
#define MUSIC_PLAYER_HEIGHT 800

#define MUSIC_TITLEBAR_WIDTH 480
#define MUSIC_TITLEBAR_HEIGHT 30

#define MUSIC_LYRICVIEW_WIDTH 480
#define MUSIC_LYRICVIEW_HEIGHT 480
#define MUSIC_LYRICVIEWITEM_WIDTH 480
#define MUSIC_LYRICVIEWITEM_HEIGHT 30 

#define MUSIC_PROGRESSMUSIC_WIDTH 350
#define MUSIC_PROGRESSMUSIC_HEIGHT 20


#endif
